-- AlterTable
ALTER TABLE "nse_candles" ALTER COLUMN "open" DROP NOT NULL,
ALTER COLUMN "high" DROP NOT NULL,
ALTER COLUMN "low" DROP NOT NULL,
ALTER COLUMN "close" DROP NOT NULL,
ALTER COLUMN "volume" DROP NOT NULL;
